// Code generated by bpf2go; DO NOT EDIT.
// bpf2go -target bpfel,bpfeb -go-package euc tcpconnect ./bpf/tcpconnect.c
// Regeneration requires clang + kernel headers; run on a Linux CI/maintainer
// machine: go generate ./internal/collector/euc/...
// The agent binary embeds the precompiled object; no clang needed at build time.

//go:build (386 || amd64 || arm || arm64 || loong64 || mips64el || mipsle || ppc64le || riscv64 || s390x) && linux

package euc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

//go:embed tcpconnect_bpfel.o
var _TcpconnectBytes []byte

// tcpconnectSpecs contains the eBPF program and map specifications.
type tcpconnectSpecs struct {
	tcpconnectProgramSpecs
	tcpconnectMapSpecs
}

// tcpconnectProgramSpecs holds the BPF program specs.
type tcpconnectProgramSpecs struct {
	HandleTcpV4Connect *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV6Connect *ebpf.ProgramSpec `ebpf:"handle_tcp_v6_connect"`
}

// tcpconnectMapSpecs holds the BPF map specs.
type tcpconnectMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// tcpconnectObjects holds the loaded BPF objects (programs + maps).
// Callers use loadTcpconnectObjects to populate this struct.
type tcpconnectObjects struct {
	tcpconnectPrograms
	tcpconnectMaps
}

// Close releases all BPF resources held by the objects.
func (o *tcpconnectObjects) Close() error {
	return _TcpconnectClose(
		&o.tcpconnectPrograms,
		&o.tcpconnectMaps,
	)
}

// tcpconnectMaps holds the loaded BPF maps.
type tcpconnectMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

// Close releases all maps.
func (m *tcpconnectMaps) Close() error {
	return _TcpconnectClose(m.Events)
}

// tcpconnectPrograms holds the loaded BPF programs.
type tcpconnectPrograms struct {
	HandleTcpV4Connect *ebpf.Program `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV6Connect *ebpf.Program `ebpf:"handle_tcp_v6_connect"`
}

// Close releases all programs.
func (p *tcpconnectPrograms) Close() error {
	return _TcpconnectClose(
		p.HandleTcpV4Connect,
		p.HandleTcpV6Connect,
	)
}

// loadTcpconnect loads the embedded eBPF object into the kernel and returns
// the collection (spec) — the low-level alternative to loadTcpconnectObjects.
func loadTcpconnect() (*ebpf.Collection, error) {
	spec, err := loadTcpconnectSpec()
	if err != nil {
		return nil, err
	}
	return ebpf.NewCollection(spec)
}

// loadTcpconnectSpec returns the eBPF collection spec parsed from the
// embedded object without loading it into the kernel.
func loadTcpconnectSpec() (*ebpf.CollectionSpec, error) {
	reader, err := _TcpconnectReader()
	if err != nil {
		return nil, err
	}
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpconnect: %w", err)
	}
	return spec, err
}

// loadTcpconnectObjects loads the embedded eBPF object into the kernel,
// populating the provided tcpconnectObjects struct.
// opts may be nil — defaults are used.
func loadTcpconnectObjects(obj *tcpconnectObjects, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpconnectSpec()
	if err != nil {
		return err
	}
	return spec.LoadAndAssign(obj, opts)
}

// _TcpconnectReader returns an io.ReaderAt over the embedded ELF object.
func _TcpconnectReader() (io.ReaderAt, error) {
	return bytes.NewReader(_TcpconnectBytes), nil
}

// _TcpconnectClose is a helper that closes any io.Closer values, collecting
// errors and returning the first non-nil one.
func _TcpconnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if closer == nil {
			continue
		}
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}
