// Code generated by bpf2go; DO NOT EDIT.
// bpf2go -target bpfel,bpfeb -go-package euc tcpconnect ./bpf/tcpconnect.c
// Regeneration requires clang + kernel headers; run on a Linux CI/maintainer
// machine: go generate ./internal/collector/euc/...
// The agent binary embeds the precompiled object; no clang needed at build time.

//go:build (mips || mips64 || ppc64 || s390x) && linux

package euc

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

//go:embed tcpconnect_bpfeb.o
var _TcpconnectEbBytes []byte

// tcpconnectEbSpecs contains the eBPF program and map specifications (big-endian).
type tcpconnectEbSpecs struct {
	tcpconnectEbProgramSpecs
	tcpconnectEbMapSpecs
}

// tcpconnectEbProgramSpecs holds the BPF program specs (big-endian).
type tcpconnectEbProgramSpecs struct {
	HandleTcpV4Connect *ebpf.ProgramSpec `ebpf:"handle_tcp_v4_connect"`
	HandleTcpV6Connect *ebpf.ProgramSpec `ebpf:"handle_tcp_v6_connect"`
}

// tcpconnectEbMapSpecs holds the BPF map specs (big-endian).
type tcpconnectEbMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// _TcpconnectEbReader returns an io.ReaderAt over the embedded big-endian ELF object.
func _TcpconnectEbReader() (io.ReaderAt, error) {
	return bytes.NewReader(_TcpconnectEbBytes), nil
}

// loadTcpconnectEb loads the embedded big-endian eBPF object into the kernel.
func loadTcpconnectEb() (*ebpf.Collection, error) {
	spec, err := loadTcpconnectEbSpec()
	if err != nil {
		return nil, err
	}
	return ebpf.NewCollection(spec)
}

// loadTcpconnectEbSpec returns the big-endian eBPF collection spec.
func loadTcpconnectEbSpec() (*ebpf.CollectionSpec, error) {
	reader, err := _TcpconnectEbReader()
	if err != nil {
		return nil, err
	}
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpconnect (big-endian): %w", err)
	}
	return spec, err
}

// _TcpconnectEbClose closes any io.Closer values.
func _TcpconnectEbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if closer == nil {
			continue
		}
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}
